development:
  image: ${DOCKER_REPO}dev
  build: .
  dockerfile: Dockerfile.development
  volumes:
    - ./.release:/srv/postgrest/.release
    - ${HOME}/.stack-work:/srv/postgrest/.stack-work
    - ${HOME}/.stack:/root/.stack
  entrypoint: stack install --allow-different-user --local-bin-path /srv/postgrest/.release
release:
  build: .
  image: ${DOCKER_REPO}:${DOCKER_IMAGE_TAG}
