development:
  build: .
  dockerfile: Dockerfile.development
  labels:
    postgrestdev: ""
  volumes:
    - ./.release:/srv/postgrest/.release
    - ${HOME}/.stack-work:/srv/postgrest/.stack-work
    - ${HOME}/.stack:/root/.stack
release:
  build: .
