version: '2'
services:
  development:
    build:
      context: .
      dockerfile: Dockerfile.development
    image: ${DOCKER_REPO}dev
    volumes:
      - ./.release:/srv/postgrest/.release
      # - ${HOME}/.stack-work:/srv/postgrest/.stack-work
      # - ${HOME}/.stack:/root/.stack
  release:
    build: .
    image: ${DOCKER_REPO}:${DOCKER_IMAGE_TAG}
